language: node_js
node_js: 'lts/*'
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
before_script:
  - yarn
script: yarn run build
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script
    script: yarn run deploy && yarn run alias && yarn run unalias
    skip_cleanup: true
    on:
      master: true